# Generated by Django 5.2.17 on 2026-09-06 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raffle_name', models.CharField(default='Annual Community Raffle', max_length=200)),
                ('starting_ticket_number', models.PositiveIntegerField(default=1)),
                ('ending_ticket_number', models.PositiveIntegerField(default=1000)),
                ('ticket_number_padding', models.PositiveIntegerField(default=4)),
                ('default_tickets_per_column', models.PositiveIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Raffle settings',
                'verbose_name_plural': 'Raffle settings',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['active', 'cancelled'])), name='reservation_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved')], db_index=True, default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['available', 'reserved'])), name='ticket_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='ReservationTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_links', to='raffle.reservation')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_links', to='raffle.ticket')),
            ],
            options={
                'ordering': ['ticket__number'],
                'constraints': [models.UniqueConstraint(fields=('ticket', 'reservation'), name='unique_ticket_in_reservation')],
            },
        ),
    ]
