# Generated by Django 5.2.17 on 2026-09-19 04:07

import raffle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.FileField(blank=True, null=True, upload_to=raffle.models.ticket_design_background_path)),
                ('layout', models.JSONField(blank=True, default=list)),
                ('page_size', models.CharField(default='a4', max_length=10)),
                ('page_orientation', models.CharField(default='portrait', max_length=10)),
                ('page_columns', models.PositiveIntegerField(default=5)),
                ('page_rows', models.PositiveIntegerField(default=3)),
                ('margin_mm', models.PositiveIntegerField(default=10)),
                ('gap_mm', models.PositiveIntegerField(default=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket design',
                'verbose_name_plural': 'Ticket design',
            },
        ),
    ]
